server:
  port: 8081

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com/homework/todolist/pojo

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/todo?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8

logging:
  file:
    name: ./todo/todo.log
